name: Fetch API Hits Count

on:
  schedule:
    # Run the job every 30 minutes
    - cron: "*/30 * * * *"

jobs:
  fetch_api_hits:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository to commit the data later
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Query the API and extract the "hits" count
      - name: Query API and extract hits count
        run: |
          # Query the API using curl and parse the hits count using jq
          HITS=$(curl -s https://marketplace-api.sshopencloud.eu/api/item-search?categories=&advanced=false&includeSteps=false | jq '.hits')
          mkdir -p $GITHUB_WORKSPACE/data
          echo "{\"timestamp\": \"$(date +%s)\", \"hits\": $HITS}" > $GITHUB_WORKSPACE/data/hits_$(date +%s).json

      - name: Commit and push data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Pull the latest changes from the remote
          git pull --rebase https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/mkrzmr/sshompitor.git main

            
          git add $GITHUB_WORKSPACE/data/*.json
          git commit -m "Add new hits count at $(date)" || exit 0  # Exit if no changes to commit
          
          # Use the Personal Access Token for authentication
          git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/mkrzmr/sshompitor.git
      - name: Ensure data directory exists
        run: |
          mkdir -p $GITHUB_WORKSPACE/data

      - name: Print working directory
        run: |
          pwd
          echo "Files in the current directory:"
          ls -la

      - name: Check if JSON files exist
        run: |
          echo "Listing the files in 'data/' directory:"
          ls -la $GITHUB_WORKSPACE/data/

      - name: Generate index.json with absolute path
        run: |
          ls $GITHUB_WORKSPACE/data/*.json > $GITHUB_WORKSPACE/data/index.json
          cat $GITHUB_WORKSPACE/data/index.json  # Output index.json to verify
