name: Fetch API Hits Count

on:
  schedule:
    - cron: "*/30 * * * *"  # Run every 30 minutes

jobs:
  fetch_api_hits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Query API and extract timestamp and hits
        run: |
          # Query the API
          RESPONSE=$(curl -s https://marketplace-api.sshopencloud.eu/api/item-search?categories=&advanced=false&includeSteps=false )

          # Extract the timestamp and hits using jq
          TIMESTAMP=$(echo $RESPONSE | jq -r '.timestamp')
          HITS=$(echo $RESPONSE | jq -r '.hits.hits')

          # Create a directory for storing data
          mkdir -p $GITHUB_WORKSPACE/data

          # Save the result in the format {timestamp: hits}
          echo "{\"$TIMESTAMP\": $HITS}" > $GITHUB_WORKSPACE/data/hits_$TIMESTAMP.json

      - name: Commit and push data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Pull the latest changes from the remote
          git pull --rebase https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/mkrzmr/sshompitor.git main

          # Add the new file(s) to the repository
          git add $GITHUB_WORKSPACE/data/*.json

          # Commit the new data with a message
          git commit -m "Add new hits count at $(date)" || exit 0  # No commit if no changes

          # Push the changes to the remote repository
          git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/mkrzmr/sshompitor.git main
