name: Fetch API Hits Count

on:
  schedule:
    # Run the job every 30 minutes
    - cron: "*/30 * * * *"

jobs:
  fetch_api_hits:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository to commit the data later
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Query the API and extract the "hits" count
      - name: Query API and extract hits count
        run: |
          # Query the API using curl and parse the hits count using jq
          HITS=$(curl -s https://api.example.com/items | jq '.hits')
          
          # Create a 'data' directory if it doesn't exist
          mkdir -p data
          
          # Save the hits count with a timestamp in a JSON file
          echo "{\"timestamp\": \"$(date +%s)\", \"hits\": $HITS}" > data/hits_$(date +%s).json

      # Step 3: Commit and push the new data to the repository
      - name: Commit and push data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add the new file to the repository
          git add data/*.json
          
          # Commit the new data with a message
          git commit -m "Add new hits count at $(date)"
          
          # Push the commit to the repository
          git push
          # Generate an index.json file that lists all JSON files in the 'data/' directory
      - name: Generate index.json
        run: |
          ls data/*.json | jq -R -s -c 'split("\n")[:-1]' > data/index.json
