name: Fetch API Full Responses

on:
  schedule:
    - cron: "0 1 * * *"  # Run every day
  workflow_dispatch:

jobs:
  fetch_api_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Query API and store full responses for categories and sources
        run: |
          # Generate the current timestamp (Unix time in seconds)
          TIMESTAMP=$(date +%s)
          # Create directories for storing data
          mkdir -p $GITHUB_WORKSPACE/data
          mkdir -p $GITHUB_WORKSPACE/data/full

          #### Fetch full category data ####
          declare -A ENDPOINTS=(
            ["tool-or-service"]="https://marketplace-api.sshopencloud.eu/api/item-search?categories=tool-or-service&advanced=false&includeSteps=false"
            ["training-material"]="https://marketplace-api.sshopencloud.eu/api/item-search?categories=training-material&advanced=false&includeSteps=false"
            ["publication"]="https://marketplace-api.sshopencloud.eu/api/item-search?categories=publication&advanced=false&includeSteps=false"
            ["dataset"]="https://marketplace-api.sshopencloud.eu/api/item-search?categories=dataset&advanced=false&includeSteps=false"
            ["workflow"]="https://marketplace-api.sshopencloud.eu/api/item-search?categories=workflow&advanced=false&includeSteps=false"
          )

          # Initialize JSON file for categories
          echo "{\"$TIMESTAMP\": {" > $GITHUB_WORKSPACE/data/full/categories_full.json
          FIRST_CATEGORY=true
          for CATEGORY in "${!ENDPOINTS[@]}"; do
            RESPONSE=$(curl -s "${ENDPOINTS[$CATEGORY]}")
            if [ "$FIRST_CATEGORY" = true ]; then
              echo "\"$CATEGORY\": $RESPONSE" >> $GITHUB_WORKSPACE/data/full/categories_full.json
              FIRST_CATEGORY=false
            else
              echo ", \"$CATEGORY\": $RESPONSE" >> $GITHUB_WORKSPACE/data/full/categories_full.json
            fi
          done
          echo "}}" >> $GITHUB_WORKSPACE/data/full/categories_full.json

          #### Fetch full source data ####
          SOURCES_RESPONSE=$(curl -s "https://marketplace-api.sshopencloud.eu/api/sources")
          SOURCE_IDS=$(echo $SOURCES_RESPONSE | jq -r '.sources[] | .id')

          echo "{\"$TIMESTAMP\": {" > $GITHUB_WORKSPACE/data/full/sources_full.json
          FIRST_SOURCE=true
          for SOURCE_ID in $SOURCE_IDS; do
            SOURCE_RESPONSE=$(curl -s "https://marketplace-api.sshopencloud.eu/api/sources/$SOURCE_ID/items")
            SOURCE_LABEL=$(curl -s "https://marketplace-api.sshopencloud.eu/api/sources" | jq -r --arg id "$SOURCE_ID" '.sources[] | select(.id == ($id|tonumber)) | .label // "Unknown Source"')
            SAFE_LABEL=$(echo "$SOURCE_LABEL" | sed 's/[^[:print:]]//g')

            if [ "$FIRST_SOURCE" = true ]; then
              echo "\"$SAFE_LABEL\": $SOURCE_RESPONSE" >> $GITHUB_WORKSPACE/data/full/sources_full.json
              FIRST_SOURCE=false
            else
              echo ", \"$SAFE_LABEL\": $SOURCE_RESPONSE" >> $GITHUB_WORKSPACE/data/full/sources_full.json
            fi
          done
          echo "}}" >> $GITHUB_WORKSPACE/data/full/sources_full.json

      - name: Commit and push full category responses
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --no-rebase https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/mkrzmr/sshompitor.git main
          git add $GITHUB_WORKSPACE/data/full/categories_full.json
          git commit -m "Add full category responses at $(date)" || exit 0
          git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/mkrzmr/sshompitor.git main

      - name: Commit and push full source responses
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --no-rebase https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/mkrzmr/sshompitor.git main
          git add $GITHUB_WORKSPACE/data/full/sources_full.json
          git commit -m "Add full source responses at $(date)" || exit 0
          git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/mkrzmr/sshompitor.git main
