name: Fetch API Hits Count

on:
  schedule:
    - cron: "0 1 * * *"  # Run every day
  workflow_dispatch:

jobs:
  fetch_api_hits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Query API and extract hits for categories and sources
        run: |
          TIMESTAMP=$(date +%s)
          mkdir -p $GITHUB_WORKSPACE/data

          declare -A ENDPOINTS=(
            ["tool-or-service"]="https://marketplace-api.sshopencloud.eu/api/item-search?categories=tool-or-service&advanced=false&includeSteps=false"
            ["training-material"]="https://marketplace-api.sshopencloud.eu/api/item-search?categories=training-material&advanced=false&includeSteps=false"
            ["publication"]="https://marketplace-api.sshopencloud.eu/api/item-search?categories=publication&advanced=false&includeSteps=false"
            ["dataset"]="https://marketplace-api.sshopencloud.eu/api/item-search?categories=dataset&advanced=false&includeSteps=false"
            ["workflow"]="https://marketplace-api.sshopencloud.eu/api/item-search?categories=workflow&advanced=false&includeSteps=false"
          )

          echo "{\"$TIMESTAMP\": {" > $GITHUB_WORKSPACE/data/full_items.json
          echo "{\"$TIMESTAMP\": {" > $GITHUB_WORKSPACE/data/items.json
          CATEGORY_ZERO_HITS=true
          FIRST=true

          for CATEGORY in "${!ENDPOINTS[@]}"; do
            RESPONSE=$(curl -s "${ENDPOINTS[$CATEGORY]}")
            echo "\"$CATEGORY\": $RESPONSE" >> $GITHUB_WORKSPACE/data/full_items.json
            HITS=$(echo "$RESPONSE" | jq -r '.hits // 0')

            if [ "$FIRST" = true ]; then
              echo "\"$CATEGORY\": $HITS" >> $GITHUB_WORKSPACE/data/items.json
              FIRST=false
            else
              echo ", \"$CATEGORY\": $HITS" >> $GITHUB_WORKSPACE/data/items.json
              echo ", \"$CATEGORY\": $RESPONSE" >> $GITHUB_WORKSPACE/data/full_items.json
            fi

            if [ "$HITS" -gt 0 ]; then
              CATEGORY_ZERO_HITS=false
            fi
          done

          echo "}}" >> $GITHUB_WORKSPACE/data/items.json
          echo "}}" >> $GITHUB_WORKSPACE/data/full_items.json

          if [ "$CATEGORY_ZERO_HITS" = true ]; then
            echo "All category hits returned 0. API might be down. Skipping this run."
            exit 0
          fi

          SOURCES_RESPONSE=$(curl -s "https://marketplace-api.sshopencloud.eu/api/sources")
          echo "{\"$TIMESTAMP\": $SOURCES_RESPONSE}" > $GITHUB_WORKSPACE/data/full_sources.json
          SOURCE_IDS=$(echo $SOURCES_RESPONSE | jq -r '.sources[] | .id')

          echo "{\"$TIMESTAMP\": {" > $GITHUB_WORKSPACE/data/sources.json
          FIRST_SOURCE=true
          SOURCE_ZERO_HITS=true

          for SOURCE_ID in $SOURCE_IDS; do
            SOURCE_RESPONSE=$(curl -s "https://marketplace-api.sshopencloud.eu/api/sources/$SOURCE_ID/items")
            SOURCE_HITS=$(echo "$SOURCE_RESPONSE" | jq -r '.hits // 0')
            SOURCE_LABEL=$(echo $SOURCES_RESPONSE | jq -r --arg id "$SOURCE_ID" '.sources[] | select(.id == ($id|tonumber)) | .label // "Unknown Source"')
            SAFE_LABEL=$(echo "$SOURCE_LABEL" | sed 's/[^[:print:]]//g')

            if [ "$FIRST_SOURCE" = true ]; then
              echo "\"$SAFE_LABEL\": $SOURCE_HITS" >> $GITHUB_WORKSPACE/data/sources.json
              FIRST_SOURCE=false
            else
              echo ", \"$SAFE_LABEL\": $SOURCE_HITS" >> $GITHUB_WORKSPACE/data/sources.json
            fi

            if [ "$SOURCE_HITS" -gt 0 ]; then
              SOURCE_ZERO_HITS=false
            fi
          done

          echo "}}" >> $GITHUB_WORKSPACE/data/sources.json

          if [ "$SOURCE_ZERO_HITS" = true ]; then
            echo "All source hits returned 0. API might be down. Skipping this run."
            exit 0
          fi

      - name: Commit and push category hits to items.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --no-rebase https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/mkrzmr/sshompitor.git main

          if [ ! -f items.json ]; then
            echo "{}" > items.json
          fi

          jq -s '.[0] * .[1]' $GITHUB_WORKSPACE/data/items.json items.json > $GITHUB_WORKSPACE/data/merged_items.json
          mv $GITHUB_WORKSPACE/data/merged_items.json items.json

          git rm --cached $GITHUB_WORKSPACE/data/items.json || true
          git add items.json
          git commit -m "Add new hits count at $(date)" || exit 0
          git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/mkrzmr/sshompitor.git main

      - name: Commit and push source hits to sources.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --no-rebase https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/mkrzmr/sshompitor.git main

          if [ ! -f sources.json ]; then
            echo "{}" > sources.json
          fi

          jq -s '.[0] * .[1]' $GITHUB_WORKSPACE/data/sources.json sources.json > $GITHUB_WORKSPACE/data/merged_sources.json
          mv $GITHUB_WORKSPACE/data/merged_sources.json sources.json

          git rm --cached $GITHUB_WORKSPACE/data/sources.json || true
          git add sources.json
          git commit -m "Add new source hits count at $(date)" || exit 0
          git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/mkrzmr/sshompitor.git main

      - name: Commit and push full_items.json (timestamped)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --no-rebase https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/mkrzmr/sshompitor.git main

          TIMESTAMP=$(jq -r 'keys[0]' $GITHUB_WORKSPACE/data/full_items.json)
          FILE_NAME="full_items_${TIMESTAMP}.json"
          cp $GITHUB_WORKSPACE/data/full_items.json $FILE_NAME

          git add "$FILE_NAME"
          git commit -m "Add full API snapshot for $TIMESTAMP" || exit 0
          git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/mkrzmr/sshompitor.git main
